apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: inventory
data:
  DB_HOST: db
  DB_PORT: "5432"
  DB_NAME: inventory_db
  REACT_APP_API_URL: "http://54.90.137.148:5000"

